git-commit-id:
  build-version: ${git.build.version}
  build-time: ${git.build.time}
  git-branch: ${git.branch}
  git-commit-id: ${git.commit.id}
  git-commit-message: ${git.commit.message.full}

maven-profile: ${profile-id}

security:
  enabled: false

file-scan:
  enabled: false
  info:
    directory-info-list:
      -
        "path": deliveryservice-application/src/main/resources/directories/directory-1
        "time": 10-08-2021 11:09:30
      -
        "path": deliveryservice-application/src/main/resources/directories/directory-2
        "time": 10-08-2021 11:09:35
      -
        "path": deliveryservice-application/src/main/resources/directories/directory-3
        "time": 10-08-2021 11:09:39

spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelogs/changelog-master.xml

  datasource:
    url: jdbc:sqlserver://localhost:1433;database=deliveryservice
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: pavel.avtaev
    password: password

  jpa:
    generate-ddl: false
    show-sql: true
    open-in-view: false