git-commit-id:
  build-version: ${git.build.version}
  build-time: ${git.build.time}
  git-branch: ${git.branch}
  git-commit-id: ${git.commit.id}
  git-commit-message: ${git.commit.message.full}

spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelogs/changelog-master.xml

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password

  jpa:
    generate-ddl: false
    show-sql: true
    open-in-view: false